# Generated by Django 6.0.2 on 2026-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=2)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adult_capacity', models.IntegerField(default=2)),
                ('children_capacity', models.IntegerField(default=1)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_air_condition', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite')], default='single', max_length=20)),
                ('room_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
    ]
