# Generated by Django 6.0.2 on 2026-02-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'الغرفة', 'verbose_name_plural': 'الغرف'},
        ),
    ]
