# Generated by Django 6.0.2 on 2026-02-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='adult_capacity',
            field=models.IntegerField(default=2, verbose_name='أماكن الكبار'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='السعة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='children_capacity',
            field=models.IntegerField(default=1, verbose_name='أماكن الصغار'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='الطابق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_air_condition',
            field=models.BooleanField(default=True, verbose_name='مكيف الهواء'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True, verbose_name='التلفاز'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True, verbose_name='الأنترنت wifi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='صور'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='التوفر'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الليلة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='رقم الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('maintenance', 'Under Maintenance')], default='available', max_length=20, verbose_name='حالة الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite')], default='single', max_length=20, verbose_name='نوع الغرفة'),
        ),
    ]
