# Generated by Django 6.0.2 on 2026-02-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الإسم')),
                ('last_name', models.CharField(max_length=50, verbose_name='اللقب')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='مكان الميلاد')),
                ('address', models.TextField(verbose_name='عنوان السكن')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('id_type', models.CharField(choices=[('national_id', 'بطاقة تعريف وطنية'), ('passport', 'جواز سفر'), ('driver_license', 'رخصة سياقة')], default='national_id', max_length=20, verbose_name='نوع الهوية')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الهوية')),
                ('id_issue_date', models.DateField(verbose_name='تاريخ صدور الهوية')),
                ('id_issuing_authority', models.CharField(max_length=100, verbose_name='السلطة الصادرة للهوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
