# Generated by Django 6.0.2 on 2026-02-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'النزيل', 'verbose_name_plural': 'النزلاء'},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='تاريخ الدخول')),
                ('check_out_date', models.DateField(verbose_name='تاريخ الخروج')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('checked_out', 'تم المغادرة')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_guest', to='bookings.guest', verbose_name='النزيل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='rooms.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
            },
        ),
    ]
