# Generated by Django 6.0.2 on 2026-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_guest_options_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.CharField(default='جزائري', max_length=50, verbose_name='الجنسية'),
        ),
    ]
